/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_estar_Holography_RenderDrawByC */

#ifndef _Included_com_estar_Holography_RenderDrawByC
#define _Included_com_estar_Holography_RenderDrawByC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_estar_Holography_RenderDrawByC
 * Method:    drawRender
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_estar_Holography_RenderDrawByC_drawRender
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_estar_Holography_RenderDrawByC
 * Method:    drawRender2D
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_estar_Holography_RenderDrawByC_drawRender2D
  (JNIEnv *, jclass, jint, jint);
  
JNIEXPORT jint JNICALL Java_com_estar_Holography_RenderDrawByC_setPercent
  (JNIEnv *, jclass, jfloat, jfloat);
  
JNIEXPORT jint JNICALL Java_com_estar_Holography_RenderDrawByC_drawRender2DR
  (JNIEnv *, jclass, jint, jint);
  
JNIEXPORT jint JNICALL Java_com_estar_Holography_RenderDrawByC_drawRender2DTop
  (JNIEnv *, jclass, jint, jint);

JNIEXPORT jint JNICALL Java_com_estar_Holography_RenderDrawByC_drawRender2DBottom
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
